#!/usr/bin/env bash
# update-skills-index.sh
# skills/ 디렉토리를 스캔하여 README.md의 Skills 목록 부분만 갱신한다.
# README의 나머지 섹션(Installation, Compatibility 등)은 건드리지 않는다.
#
# 동작: <!-- SKILLS_START --> 와 <!-- SKILLS_END --> 마커 사이를 교체.
#
# Usage: bash scripts/update-skills-index.sh
# Requires: bash 4+ (macOS: brew install bash)

KIRO_DIR="$HOME/.kiro"
SKILLS_DIR="$KIRO_DIR/skills"
README="$KIRO_DIR/README.md"
START_MARKER="<!-- SKILLS_START - Do not edit between these markers. Generated by update-skills-index.sh -->"
END_MARKER="<!-- SKILLS_END -->"

# Check README exists and has markers
if [[ ! -f "$README" ]]; then
  echo "❌ README.md not found at $README"
  exit 1
fi

if ! grep -q "SKILLS_START" "$README"; then
  echo "❌ README.md missing SKILLS_START marker. Add this line where you want the skills list:"
  echo "   $START_MARKER"
  exit 1
fi

# SKILL.md에서 description 첫 줄 추출
get_description() {
  local skill_md="$1/SKILL.md"
  if [[ -f "$skill_md" ]]; then
    sed -n '/^description:/,/^[a-z]/{ /^description:/{ s/^description: *//; s/|//; p; d }; /^  /{ s/^  *//; p; q } }' "$skill_md" | head -1 | sed 's/^ *//;s/ *$//'
  fi
}

# 카테고리 분류
categorize_skill() {
  local name="$1"
  case "$name" in
    aws-*|api-gateway|supabase-postgres|terraform-skill)
      echo "AWS & Cloud";;
    k8s-*|docker-*|helm-*|gitops-*|observability)
      echo "Platform & Infra";;
    kafka-*|nodejs-kafka|elasticsearch-*|dynamodb|rdb-*|pg-*|iot-*|event-validation-*)
      echo "Data & Messaging";;
    typescript-*|nodejs-*|java-*|kotlin-*|spring-*|api-design|architecture|git-*|coding-principles|contract-*|testcontainers-*|opensearch-node)
      echo "Development";;
    jira-*|sprint-*|knowledge-*|scope-*|skill-*|project-*|repo-docs-sync)
      echo "Workflow & Management";;
    *)
      echo "Other";;
  esac
}

# 스킬 목록 수집
declare -A CATEGORIES

for skill_dir in "$SKILLS_DIR"/*/; do
  [[ -d "$skill_dir" ]] || continue
  skill_name=$(basename "$skill_dir")
  [[ -f "$skill_dir/SKILL.md" ]] || continue
  # Skip private skills (underscore prefix)
  [[ "$skill_name" == _* ]] && continue
  
  category=$(categorize_skill "$skill_name")
  desc=$(get_description "$skill_dir")
  
  if [[ -z "${CATEGORIES[$category]}" ]]; then
    CATEGORIES[$category]="$skill_name|$desc"
  else
    CATEGORIES[$category]="${CATEGORIES[$category]}"$'\n'"$skill_name|$desc"
  fi
done

# 스킬 수 계산 (public only)
total_skills=0
for skill_dir in "$SKILLS_DIR"/*/; do
  [[ -f "$skill_dir/SKILL.md" ]] || continue
  skill_name=$(basename "$skill_dir")
  [[ "$skill_name" == _* ]] && continue
  ((total_skills++))
done

# steering 수 계산 (public only)
total_steering=0
for f in "$KIRO_DIR/steering/"*.md; do
  [[ -f "$f" ]] || continue
  fname=$(basename "$f")
  [[ "$fname" == _* ]] && continue
  ((total_steering++))
done

# 생성할 스킬 목록 콘텐츠
SKILLS_CONTENT=$(mktemp)

cat >> "$SKILLS_CONTENT" << EOF

### Steering

| File | Trigger | Scope |
|------|---------|-------|
EOF

for steering_file in "$KIRO_DIR/steering/"*.md; do
  [[ -f "$steering_file" ]] || continue
  fname=$(basename "$steering_file")
  [[ "$fname" == _* ]] && continue
  
  inclusion=$(sed -n 's/^inclusion: *//p' "$steering_file" | head -1)
  pattern=$(sed -n 's/^fileMatchPattern: *//p' "$steering_file" | sed "s/['\"]//g" | head -1)
  
  if [[ "$inclusion" == "fileMatch" && -n "$pattern" ]]; then
    trigger="\`$pattern\`"
  elif [[ "$inclusion" == "manual" ]]; then
    trigger="manual (#)"
  else
    trigger="always"
  fi
  
  scope=$(grep -m1 '^#' "$steering_file" | sed 's/^# *//')
  [[ -z "$scope" ]] && scope="$fname"
  
  echo "| $fname | $trigger | $scope |" >> "$SKILLS_CONTENT"
done

echo "" >> "$SKILLS_CONTENT"
echo "### Skills by Category" >> "$SKILLS_CONTENT"
echo "" >> "$SKILLS_CONTENT"

# 카테고리 순서 고정
for category in "AWS & Cloud" "Platform & Infra" "Data & Messaging" "Development" "Workflow & Management" "Other"; do
  [[ -z "${CATEGORIES[$category]}" ]] && continue
  
  echo "**${category}**" >> "$SKILLS_CONTENT"
  echo "" >> "$SKILLS_CONTENT"
  
  echo "${CATEGORIES[$category]}" | sort | while IFS='|' read -r name desc; do
    if [[ -n "$desc" ]]; then
      echo "- \`$name\` — $desc" >> "$SKILLS_CONTENT"
    else
      echo "- \`$name\`" >> "$SKILLS_CONTENT"
    fi
  done
  
  echo "" >> "$SKILLS_CONTENT"
done

# README에서 마커 사이를 교체
# 1. 마커 앞 부분 추출
sed -n "1,/^$START_MARKER/p" "$README" > "${README}.tmp"

# 2. 새 스킬 콘텐츠 삽입
cat "$SKILLS_CONTENT" >> "${README}.tmp"

# 3. 마커 뒷 부분 추출 (END_MARKER 포함해서 이후 전부)
sed -n "/^$END_MARKER/,\$p" "$README" >> "${README}.tmp"

# 4. 교체
mv "${README}.tmp" "$README"
rm -f "$SKILLS_CONTENT"

# badge 숫자 업데이트
sed -i "s/Skills-[0-9]*-/Skills-${total_skills}-/" "$README"
sed -i "s/Steering-[0-9]*-/Steering-${total_steering}-/" "$README"

echo "✅ README.md skills index updated (${total_skills} skills, ${total_steering} steering)"
echo "   Other sections preserved (Installation, Compatibility, etc.)"
